# Generated by Django 5.2.4 on 2025-08-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_share_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, help_text='Caption for photos/videos', max_length=500),
        ),
    ]
