# Generated by Django 5.2.4 on 2025-08-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text='YouTube video ID for reels', max_length=20, null=True),
        ),
    ]
